# Generated by Django 3.0 on 2023-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=20)),
                ('nme', models.CharField(max_length=120)),
                ('em', models.EmailField(max_length=150)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
